### ISSUE TITLE
Add aspect ratio dropdown or width/height input  for easier composition on different resolution generation

### ISSUE THREAD

**Issue by em0xi0nx** [Fuwuffyi/ComfyUI-VisualArea-Nodes#3]
Hi, i tried to play with the node and i just notice that maybe you could add width and height or aspect ratio inputs, whatever is easier or make sense. i think it will improve and it'll be easier to compose with these options. 

thank you so much for doing a good job and for your hard work!!

**Comment by Fuwuffyi** [comment]
Hey, thank you for your feedback, I really appreciate it!

I have recently added that feature not too long ago to improve the node, adding a width/hight widget to it.
(You might also need update and replace the node as I have been renaming some of the inputs too)

**Comment by em0xi0nx** [comment]
Cool thanks!! i've been looking for alternative for area composition and this really is a life saver. you're the best man!! cheers!! 🎉🎉🎉
