### ISSUE TITLE
Node is freezing Interface

### ISSUE THREAD

**Issue by balkerz666** [Fuwuffyi/ComfyUI-VisualArea-Nodes#4]
Hello,
when I add Visual Area Prompt node to my workflow, my ComfyUI interface freezes.
Is this an already known issue?

**Comment by PixelDroidUK** [comment]
Ditto...multiple browsers tested, as soon as the VAP node is added, nothing, can't navigate the workflow or do anything, completely locked!

**Comment by Fuwuffyi** [comment]
It seems to be working on my end.

Could you send the output of your browser's console if there are any errors there?
Which versions of the node/comfyui are you using?
Have you tried updating?
Have you tried creating a new workflow with the node to see if the issue persists even in newer workflows?

It could also be happening because I have slowly updated the node overtime, and the js code does not work properly with the older version node.

Sorry for the inconvenience.

**Comment by balkerz666** [comment]
I'm running the latest ComfyUI v0.2.2.
Python dependencies are also up to date.
No errors in Chrome's DevTools Console.
I've also tried using the node in an empty workflow.

**Comment by PixelDroidUK** [comment]
Hi

No apology necessary, very grateful for your efforts and making the node available, I look forward to being to make use of it hopefully.

Attached log file from Opera, though I can't see anything obviously problematic.

I am using the latest version of Comfy (0.2.2)

I installed the VisualArea node via the Comfy Manager initially, and the version was dated 25.8.24, I have now manually installed from Git directly and the version is now dated 16.9.24, however the issue remains sadly.

[localhost-1726568118369.log](https://github.com/user-attachments/files/17026837/localhost-1726568118369.log)

**Comment by PixelDroidUK** [comment]
I may have incorrectly read the update date from another node, so perhaps this line was irrelevant, sorry!

> I installed the VisualArea node via the Comfy Manager initially, and the version was dated 25.8.24,

**Comment by milewski** [comment]
This error is thrown to the console when the node is added, which freezes everything...:

![image](https://github.com/user-attachments/assets/acfc72a3-9678-4580-b51d-6e6b9772bb29)


----

Steps to reproduce:

1 - Create a default workflow
2 - Add the Visual Area Prompt
3 - See the UI crashing...

**Comment by Fuwuffyi** [comment]
I have created a new branch called "dev", try cloning it manually in the custom_nodes dir, and check if the problem persists.

**Comment by milewski** [comment]
Just tried, it works 👍

**Comment by Fuwuffyi** [comment]
> Just tried, it works 👍

Glad to hear, will leave the issue open for a bit just in case the issue persists. Will merge to master.

**Comment by PixelDroidUK** [comment]
Many thanks, looks to be working fine, no freezing - yet to actually use the node but no reason to think it won't work as expected. Appreciate the quick responses and fix, thank you.

**Comment by milewski** [comment]
I found an issue, if you try to copy the node.. the UI breaks again... with the following error:

![image](https://github.com/user-attachments/assets/11d68307-5539-461b-bdb3-b721e4999419)

You dont even need to paste, just select the node and press control + C .. and the UI is broken...

**Comment by Fuwuffyi** [comment]
ComfyUI seems to create a new node on CTRL+C, and then a new one on CTRL+V. 
The UI breaking issue happens because an html canvas gets created but not linked to the actual node when copying it.

**Comment by Fuwuffyi** [comment]
I have made the canvas hidden on generation, so that the issue is no longer there.
(I mean, it still is there, just does not break the UI)
