### ISSUE TITLE
'list' object has no attribute 'out'

### ISSUE THREAD

**Issue by fhaifhai** [Fuwuffyi/ComfyUI-VisualArea-Nodes#5]
Hi, I ran into an issue trying to use this node: When trying to run the prompt, I got the following error message:

# ComfyUI Error Report
## Error Details
- **Node Type:** VisualAreaPrompt
- **Exception Type:** AttributeError
- **Exception Message:** 'list' object has no attribute 'out'
## Stack Trace
```
  File "C:\Users\xxxxx\AIP\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\xxxxx\AIP\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\xxxxx\AIP\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\xxxxx\AIP\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\xxxxx\AIP\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VisualArea-Nodes\nodes\visual_area_prompt.py", line 43, in run_node
    cond = conditionings[i].out(0)
           ^^^^^^^^^^^^^^^^^^^^

```
Would anyone be able to help me with that?

**Comment by Fuwuffyi** [comment]
That's my bad.
I have renamed a couple of nodes and accidentally the newer node has the same name as the old one.
You just need to replace the node in the workflow and everything should work again.
(Won't happen again, sorry)

**Comment by kanadiou** [comment]
Hi,
i'm sorry but i have the same issue. i am update, i don"t understand the workaround ?

**Comment by Fuwuffyi** [comment]
> Hi, i'm sorry but i have the same issue. i am update, i don"t understand the workaround ?

You just need to remove the node, then add a new one.
Again, sorry for the inconvenience

**Comment by kanadiou** [comment]
thank you, but i tried from scratch, i can'tfigured out to make it works.
i still have the error

**Comment by Fuwuffyi** [comment]
I seem to have found the issue.
Try to update the node and reach back if the issue persists, sorry for taking so long.

**Comment by fhaifhai** [comment]
awesome, it is working! now I just have to find a way to prompt it properly 😆

**Comment by kanadiou** [comment]
yes it works now, thanks !

**Comment by vu0tran** [comment]
Hm, still getting the issue despite updating the node?
