### ISSUE TITLE
Add ability to connect input integer noodles for width/height

### ISSUE THREAD

**Issue by klromans557** [Fuwuffyi/ComfyUI-VisualArea-Nodes#6]
Node works great so far!

### Problem:
Width/Height widgets cannot be used as inputs from integer nodes.

While testing, I noticed that when you set the width/height widgets to input that I could not use integers (or floats). When forced, by using a SD Any Converter node, I received an error message about the index being out of bounds.

![error_report](https://github.com/user-attachments/assets/2d28e6fe-3454-4b6e-8c4c-3df5f508d5a8)

### Requested Solution:
Please add the ability for the VisualAreaPrompt nodes to accept integer values for the width/height of the main scene. This way, we could change the size/aspect ratio of the empty latent as well as the VisualArea conditioning at the same time.

**Comment by Fuwuffyi** [comment]
Yeah sure, I'll try to fix that issue in the next couple of days.
Could take a bit longer due to university though!

**Comment by Fuwuffyi** [comment]
Okay, the issue should be fixed.
If there's any issue with it still do send it here, I will close this issue in a couple of days.

**Comment by klromans557** [comment]
Works great! Thank you very much.
