### ISSUE TITLE
Can't find a working example of the workflow

### ISSUE THREAD

**Issue by manchuwook** [Fuwuffyi/ComfyUI-VisualArea-Nodes#7]
Whenever I generate, it shows a badly garbled image that doesn't follow the area prompts.  Do you have a working example that I can yoink?  I am using an SDXL model to render.  Does this only work with SD 1.5?
![workflow](https://github.com/user-attachments/assets/7a5b3f42-3620-43e0-abed-0d8ef2239931)
![PB-_temp_nlpnf_00001_](https://github.com/user-attachments/assets/513fbd09-fdd9-4903-a3b1-faab55e92b3f)

**Comment by Fuwuffyi** [comment]
I'll definitely add some basic workflows over the next couple of months (and fix some other bugs with the probably currently unstable node)
University is giving me barely free time so it's gonna take a while for me to get around to this

**Comment by manchuwook** [comment]
I completely understand! Real life gets in the way of coding :D

I got it working, though I don't fully understand it. :/  With the stuff I have currently - it doesn't seem to obey the white background part.  Here is an image that I could template-ize and provide as a workflow

<img width="774" alt="image" src="https://github.com/user-attachments/assets/e73c08e1-8255-46f4-93f5-d2ff07c3a14b" />

**Comment by andreszs** [comment]
[Here's a full workflow](https://www.andreszsogon.com/comfyui-workflow-with-visual-area-prompt-node/) explained to use the **Visual Area Prompt** node, anyone is free to download and test it.

**Comment by manchuwook** [comment]
Holy cow, that is amazing!  Just what I needed.  Thank you.
